DELETE http://localhost:3003/api/recipes/5e1319a7c611f8121f959f6b
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcyIsImlkIjoiNWUxMzEyNTZhMjU4ZjMwYzhlZjYxZjdhIiwiaWF0IjoxNTc4MzA4MjUyfQ.U_cQtHyOonBsbUBWnL3VSBWKR-tigpTx58V2P0XE38Y