DELETE http://localhost:3000/recipes/5e11ec2aabb4d804336ca1cf Content-Type: application/json 
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlMTFlYzE0YWJiNGQ4MDQzMzZjYTFjZSIsImlhdCI6MTU3ODIzMjkzNX0
.7F0Dspz77O6WgKVxn_dhui8Wx8QtzKcoDDasoDQt4Dk