POST http://localhost:3003/api/recipes 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcyIsImlkIjoiNWUxMzEyNTZhMjU4ZjMwYzhlZjYxZjdhIiwiaWF0IjoxNTc4MzA4MjUyfQ.U_cQtHyOonBsbUBWnL3VSBWKR-tigpTx58V2P0XE38Y

{
    "title": "Test",
    "category": "Meat",
    "ingredient":["meat"],
    "instruction":"meat",
    "userId":"5e131256a258f30c8ef61f7a"
}